### ISSUE TITLE
apt-maven-plugin with maven-release-plugin fails (NPE)

### ISSUE THREAD

**Issue by guersel** [querydsl/apt-maven-plugin#43]
If I use the apt-maven-plugin in combination with the maven-release-plugin then a NullpointerException will be thrown: 

```
[INFO] [INFO] --- apt-maven-plugin:1.1.3:process (default) @ [myProject]---
[INFO] An exception has occurred in the compiler (1.8.0-internal). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
[INFO] java.lang.NullPointerException
[INFO] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ComputeAnnotationSet.scan(JavacProcessingEnvironment.java:797)
[INFO] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.findAnnotationsPresent(JavacProcessingEnvironment.java:993)
[INFO] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:927)
[INFO] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:933)
[INFO] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1199)
[INFO] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1182)
[INFO] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:868)
[INFO] 	at com.sun.tools.javac.main.Main.compile(Main.java:535)
[INFO] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:141)
[INFO] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:150)
```

This happens if I try to release on jenkins with Java 8 (IBM SDK 64bit). A normal build without trying to release is successful. I use version 1.1.3 of the apt-maven-plugin and version 2.5.1 of the maven-release-plugin, configuration of the apt-maven-plugin looks like:

```
    <plugin>
			<groupId>com.mysema.maven</groupId>
				<artifactId>apt-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/target/generated-sources/java</outputDirectory>
							<processor>com.mysema.query.apt.jpa.JPAAnnotationProcessor</processor>
						</configuration>
					</execution>
				</executions>
    </plugin>
```

The release build is successful if I debug remotely via Eclipse, maybe there is a timing issue between the release- and apt-plugin?

**Comment by Shredder121** [comment]
Could you setup a minimalistic project that we can also debug?
I don't use eclipse, but we'll see if it is also reproducible via other means.

**Comment by guersel** [comment]
Thank you for the very fast response.
Unfortunately I am not able to setup a minimalistic projects which fails in the same way. It seems that this issue is project specific.

**Comment by guersel** [comment]
I solved the issue by just waiting a few seconds before executing the apt-maven-plugin. Obviously the release plugin creates threads which are in access conflict with the apt-maven-plugin. Maybe someone has another explanation.

**Comment by ddebrunner** [comment]
FYI - I'm seeing the same stack trace in a non-maven project. In my case it seems to be related to annotation processing generating a source file with annotations (e.g. @javax.annotation.Generated).

I was also seeing it intermittently, indicating there is some timing issue.

A simple case outside of our source code did not reproduce the issue.

**Comment by Shredder121** [comment]
I think that the release plugin uses a fork of the build reactor to do some logic, and therfore it theoretically could cause timing issues. (this explains the intermittent problems)
I'll look into it.

**Comment by gaetancollaud** [comment]
I have the same issue with the apt-maven-plugin:1.1.3 (current version at the time).

I'm not able to make a release.

The normal compilation is ok and the `release:prepare` went well but the `release:perform` failed.

Did you find something ? I will try to delay the plugin, but it seems tricky to me.

```` 
[INFO] [INFO]
[INFO] [INFO] --- apt-maven-plugin:1.1.3:process (default) @ keycloak-mycompany-service ---
[INFO] C:\Users\gc\workspace\mycompany\keycloak-mycompany-authenticator\target\checkout\authenticator-service\src\main\java\ch\mycompany\authenticator\event\mycompanyEventListenerProvider.java:4: error: package ch.mycompany.authenticator.data.api does not exist
[INFO] import ch.mycompany.authenticator.data.api.AuditTO;
[INFO]                                          ^
[INFO] C:\Users\gc\workspace\mycompany\keycloak-mycompany-authenticator\target\checkout\authenticator-service\src\main\java\ch\mycompany\authenticator\event\mycompanyEventListenerProvider.java:5: error: package ch.mycompany.authenticator.data.types does not exist
[INFO] import ch.mycompany.authenticator.data.types.AuditAction;
[INFO]                                            ^
[INFO] C:\Users\gc\workspace\mycompany\keycloak-mycompany-authenticator\target\checkout\authenticator-service\src\main\java\ch\mycompany\authenticator\event\mycompanyEventListenerProvider.java:6: error: package ch.mycompany.authenticator.data.types does not exist
[INFO] import ch.mycompany.authenticator.data.types.AuditElement;
[INFO]                                            ^
[INFO] C:\Users\gc\workspace\mycompany\keycloak-mycompany-authenticator\target\checkout\authenticator-service\src\main\java\ch\mycompany\authenticator\event\mycompanyEventListenerProvider.java:7: error: package ch.mycompany.authenticator.data.types does not exist
[INFO] import ch.mycompany.authenticator.data.types.AuditLevel;
[INFO]                                            ^
[INFO] C:\Users\gc\workspace\mycompany\keycloak-mycompany-authenticator\target\checkout\authenticator-service\src\main\java\ch\mycompany\authenticator\event\mycompanyEventListenerProvider.java:115: error: cannot find symbol
[INFO]  protected void auditEvent(Event event, AuditAction action) {
[INFO]                                         ^
[INFO]   symbol:   class AuditAction
[INFO]   location: class mycompanyEventListenerProvider
[INFO] C:\Users\gc\workspace\mycompany\keycloak-mycompany-authenticator\target\checkout\authenticator-service\src\main\java\ch\mycompany\authenticator\event\mycompanyEventListenerProvider.java:137: error: cannot find symbol
[INFO]  protected AuditTO getAuditTo(Event event, AuditAction action) {
[INFO]                                            ^
[INFO]   symbol:   class AuditAction
[INFO]   location: class mycompanyEventListenerProvider
[INFO] C:\Users\gc\workspace\mycompany\keycloak-mycompany-authenticator\target\checkout\authenticator-service\src\main\java\ch\mycompany\authenticator\event\mycompanyEventListenerProvider.java:137: error: cannot find symbol
[INFO]  protected AuditTO getAuditTo(Event event, AuditAction action) {
[INFO]            ^
[INFO]   symbol:   class AuditTO
[INFO]   location: class mycompanyEventListenerProvider
[INFO] 7 errors
````
